name: Generate Natives Lua

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build RedmNamedNativesCompiler --no-restore -c Release --output ./output
      
      - name: Execute App
        run: dotnet RedmNamedNativesCompiler.dll
        working-directory: ./output

      - name: Archive natives.lua
        uses: actions/upload-artifact@v2
        with:
          name: natives-lua
          path: ./output/natives.lua

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} - ${{ github.run_number }}
          name: 'Release ${{ github.ref_name }}'
          files: ./output/natives.lua
          