name: Generate Natives Lua

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release
        
      - name: Set Working Directory
        run: cd RedmNamedNativesCompiler/RedmNamedNativesCompiler/bin/Release/net8.0
      
      - name: Execute App
        run: dotnet run RedmNamedNativesCompiler.dll
        
      - name: Set Working Directory
        run: cd ../../../../../

      - name: Archive natives.lua
        uses: actions/upload-artifact@v2
        with:
          name: natives-lua
          path: RedmNamedNativesCompiler/RedmNamedNativesCompiler/bin/Release/net8.0/natives.lua

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: "Release of natives.lua"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/generated/natives.lua
          asset_name: natives.lua
          asset_content_type: text/plain